# Generated by Django 4.1.4 on 2024-03-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workos_login', '0008_remove_loginrule_jit_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrule',
            name='method',
            field=models.CharField(choices=[('mfa', 'MFA'), ('email_mfa', 'Email MFA'), ('magic', 'Passwordless Email'), ('GoogleOAuth', 'Google SSO'), ('MicrosoftOAuth', 'Microsoft SSO'), ('sso', 'SAML SSO'), ('username', 'Username/Password')], max_length=15),
        ),
    ]
