# Generated by Django 4.2 on 2025-06-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workos_login', '0009_alter_loginrule_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrule',
            name='environment',
            field=models.CharField(blank=True, choices=[('production', 'Production'), ('sandbox', 'Sandbox')], default='production', help_text='Which environment should this login rule connect to', max_length=10),
        ),
        migrations.AlterField(
            model_name='loginrule',
            name='method',
            field=models.CharField(choices=[('mfa', 'MFA'), ('email_mfa', 'Email MFA'), ('magic', 'Passwordless Email'), ('GoogleOAuth', 'Google SSO'), ('MicrosoftOAuth', 'Microsoft SSO'), ('sso', 'SAML SSO'), ('username', 'Username/Password'), ('PING', 'PING SSO')], max_length=15),
        ),
    ]
