# Generated by Django 4.2 on 2026-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workos_login', '0010_loginrule_environment_alter_loginrule_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrule',
            name='auto_update',
            field=models.BooleanField(default=True, help_text='When disabled, explicitly prevents updating user first name, last name, and email on login.This is only applicable when WORKOS_AUTO_UPDATE is enabled, otherwise auto updating is already disabled.Having this field enabled when WORKOS_AUTO_UPDATE is disabled will have no effect.'),
        ),
    ]
