# Generated by Django 4.2 on 2026-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workos_login', '0011_loginrule_auto_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrule',
            name='require_validated_email',
            field=models.BooleanField(default=False, help_text='Require email verification on first login for Username/Password users. Only applies when WORKOS_FIRST_LOGIN_EMAIL_VERIFICATION returns True for the user.'),
        ),
    ]
