# Generated by Django 4.2 on 2026-07-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workos_login', '0012_loginrule_require_validated_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrule',
            name='custom_logout_url',
            field=models.TextField(blank=True, help_text='If `Use Single Logout` is enabled, this URL can be used as a custom logout URL for the IdP. Only applies to SAML SSO.', null=True),
        ),
        migrations.AddField(
            model_name='loginrule',
            name='use_single_logout',
            field=models.BooleanField(default=False, help_text='When enabled, users will be logged out of the IdP when they log out of your application. Only applies to SAML SSO.'),
        ),
    ]
