# Generated by Django 4.2 on 2026-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workos_login', '0012_loginrule_require_validated_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrule',
            name='custom_logout_url',
            field=models.TextField(blank=True, help_text='If the SSO Logout Method is `Custom URL`, then this URL can be used as a custom logout URL for the IdP. Only applies to SAML SSO.', null=True),
        ),
        migrations.AddField(
            model_name='loginrule',
            name='sso_logout_method',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('custom_url', 'Custom URL')], default='default', help_text='Which logout method to use for SSO. Default will use the workos logout method. Custom URL will redirect to the custom logout URL if set. Only applies to SAML SSO.', max_length=15, null=True),
        ),
    ]
