# Generated by Django 4.0.6 on 2022-10-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20220812_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=1024)),
                ('location_id', models.CharField(default=None, max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_user.officelocation'),
        ),
    ]
