# Generated by Django 3.2.15 on 2023-06-04 21:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_user', '0003_officelocation_user_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officelocation',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=38, verbose_name='Company Name')),
                ('address1', models.CharField(blank=True, max_length=38, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=38, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=38, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_state_code', message='State code most consist of exactly 2 upper case characters', regex='^[A-Z]{2}$')], verbose_name='State Code')),
                ('zip', models.CharField(blank=True, max_length=5, verbose_name='5 Digit Zip')),
                ('primary', models.BooleanField(default=True, help_text='Is this the primary address for this account?')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['id'],
                'index_together': {('content_type', 'object_id')},
            },
        ),
    ]
